namespace SalesforceNET
{
    /// <summary>
    /// Errors storage.
    /// </summary>
    internal static class Errors
    {
        #region Errors

        public const string ERR_BINDING_IS_NOT_LOGGED_IN    = "Current binding is not logged in";
        public const string ERR_ID_FIELD_IS_NOT_SET         = "Id field is not set.";
        public const string ERR_ID_FIELD_IS_AUTOGENERATED   = "Id field is autogenerated and not required.";
        public const string ERR_FIELDS_ARE_EMPTY            = "Fields are empty.";
        public const string ERR_PROPERTY_NOT_FOUND          = "Property {0} of type {1} not found.";
        public const string ERR_OFFSET_GREATER_THAN_MAXIMUM = "Offset should be less than 2000 records";
        public const string ERR_WRONG_OAUTH_URL_FORMAT      = "Wrong OAuth url format";

        #endregion Errors
    }
}
